spring:
  application:
    name:
      order-manager

dubbo:
  protocol:
    name: dubbo
    port: 30000
  registry:
    address: zookeeper://127.0.0.1:2181
  config-center: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  application:
    qos:
      enable: true
